


<!--<div class="navbar navbar-inverse navbar-fixed-top" id="header">-->
    <!--<a class="navbar-brand"><img src="/images/logo.jpg" alt="Brand"></a>-->
        <!--<div class="container">-->
         <!--<div class="staff">{staff}</div>-->
            <!--<div class="navbar-header">-->
                <!--<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">-->
                    <!--<span class="sr-only">Toggle navigation</span>-->
                    <!--<span class="icon-bar"></span>-->
                    <!--<span class="icon-bar"></span>-->
                    <!--<span class="icon-bar"></span>-->
                    <!--</button>-->
                <!--</div>-->
            <!--<div class="navbar-collapse collapse" role="navigation">-->
                <!--<ul class="nav navbar-nav">-->
                    <!--&lt;!&ndash;{queue}&ndash;&gt;-->
                    <!--<li><a class="custom {cur}" onclick="queueTools.switchCustom({index})"><span class="num">{index}</span><span class="time">{time}</span></a></li>-->
                    <!--<li><a class="custom {cur}" onclick="queueTools.switchCustom({index})"><span class="num">{index}</span><span class="time">{time}</span></a></li>-->
                    <!--<li><a class="custom {cur}" onclick="queueTools.switchCustom({index})"><span class="num">{index}</span><span class="time">{time}</span></a></li>-->
                    <!--<li><a class="custom {cur}" onclick="queueTools.switchCustom({index})"><span class="num">{index}</span><span class="time">{time}</span></a></li>-->
                <!--</ul>-->
                <!--<a class="custom-add" onclick="queueTools.addCustom();">+</a>-->
                <!--<a class="custom-remove" onclick="queueTools.removeCustom();">-</a>-->
            <!--</div>-->
        <!--</div>-->
<!--</div>-->